[CFD PROCESSING]

; Gamma of the fluid (e.g. 1.4)
GAMMA_FLUID = 1.4

; Specify if you wish to normalize all the fields
NORMALIZE_DATA = False



[GRID GENERATION]

; Mesh generation method (elliptic or TFI)
MESH_GENERATION_METHOD = TFI

; Coefficients for the sigmoid stretching of the grid blocks
SIGMOID_STREAM_COEFFICIENTS = 1.5, 1, 1, 1, 1.5

; Coefficient for the stretching in the spanwise direction (unique value)
SIGMOID_SPAN_COEFFICIENT = 1.5

; Grid Orthogonality during elliptic smoothing (True or False)
GRID_ORTHOGONALITY = True

; Number of points in the streamwise direction for each block
STREAMWISE_POINTS = 41, 30, 60, 20, 35

; Number of points in the spanwise direction (only one value)
SPANWISE_POINTS = 35

; Dimensions of the coordinates in the geometry curve files (cm, m, in) to convert everything in meters
COORDINATES_FILE_UNITS = m

; Filepath of the hub,shroud and blade (multiple if needed) geometry files
HUB_COORDINATES_FILEPATH = coordinates/hub.curve
SHROUD_COORDINATES_FILEPATH = coordinates/shroud.curve

BOUNDARIES_SPLINE_ORDER = 1

; Type of trim for every block (axial or radial)
BLOCKS_TRIM_TYPE = axial, axial, axial, axial, axial



[TURBOMACHINERY DATA]

; Type of domains representated by the blocks (unbladed, rotor, or stator)
BLOCKS_TYPE = unbladed, rotor, unbladed, stator, unbladed

; Topology for the blocks (inlet, internal or outlet) to decide about the stretching type
BLOCKS_TOPOLOGY = inlet, internal, internal, internal, outlet

; RPM of the shaft for each block
SHAFT_RPM = 0, 12657, 0, 0, 0

; Type of the blade leading and trailing edge (as many as number of blades)
BLADE_INLET_TYPE = axial, axial
BLADE_OUTLET_TYPE = axial, axial

; Method used for the camber reconstruction (regression or interpolation)
BLADES_CAMBER_RECONSTRUCTION = interpolation, interpolation

; Number of blades for every blade row
BLADES_NUMBER = 22, 54

; Insert the name of the machine for plot names
MACHINE_NAME = NASAGER4


[BLADE RECONSTRUCTION]

; Percent of streamwise and spanwise portion that are extrapolated close to extremeties
BLADE_EDGES_EXTRAPOLATION_COEFFICIENT = 0.025, 0.025

; Coefficient of smoothing for gaussian filter of the blade camber normal vector
BLADE_CAMBER_SMOOTHING_COEFFICIENT = 0.5, 0.5

; Type of splines used for the blade profiles (1 or 3 usually)
BLADE_PROFILES_SPLINE_ORDER = 1, 1

BLADE_COORDINATES_FILEPATH = coordinates/rotor.curve, coordinates/stator.curve


[GENERAL]

; Verbosity
VERBOSITY = True

; Specify True if you want to visualize the plots generated by the code for debugging
VISUAL_DEBUG = no

; Specify the type of multiblock driver (single_blade, multiblock, full_machine)
MULTIBLOCK_DRIVER_TYPE = multiblock

; Specify the types of output required. Possible choices are (turbobfm, su2mesh, meridional_splines, pickle, blade)
OUTPUT_TYPE = none

PICTURES_FOLDER_PATH = Pictures

OUTPUT_DATA_FOLDER = Output

