name: unsflow

channels:
  - conda-forge

dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib=3.8
  - scikit-learn
  - ipykernel
  - nbformat
  - coolprop
  - pip

  - pip:
      - findiff
      - h5py
      - pandas
      - plotly
      - pycgns
      - pytest
      - pyvista
      - pywavelets
      - shapely
      - sympy
      - vtk