[CFD PROCESSING]

; Gamma of the fluid (e.g. 1.4)
GAMMA_FLUID = 1.4

; Mesh generation method (elliptic or TFI)
MESH_GENERATION_METHOD = TFI

; Coefficients for the sigmoid stretching of the grid blocks
SIGMOID_STREAM_COEFFICIENTS = 1.5 1.5 1.5 

; Coefficient for the stretching in the spanwise direction (unique value)
SIGMOID_SPAN_COEFFICIENT = 1.5

; Grid Orthogonality during elliptic smoothing (True or False)
GRID_ORTHOGONALITY = True

; Type of domains representated by the blocks (unbladed, rotor, or stator)
BLOCKS_TYPE = unbladed, rotor, unbladed

; Number of points in the streamwise direction for each block
STREAMWISE_POINTS = 40, 30, 40

; Number of points in the spanwise direction (only one value)
SPANWISE_POINTS = 40

; Topology for the blocks (inlet, internal or outlet) to decide about the stretching type
BLOCKS_TOPOLOGY = inlet, internal, outlet

; Scaling of the coordinates if needed
X_REF = 1

; RPM of the shaft for each block
SHAFT_RPM = 0, -17189, 0

; Dimensions of the coordinates in the geometry curve files (cm, m, in) to convert everything in meters
COORDINATES_FILE_UNITS = cm

; Filepath of the hub,shroud and blade (multiple if needed) geometry files
HUB_COORDINATES_FILEPATH = coordinates/hub_long_inlet.curve
SHROUD_COORDINATES_FILEPATH = coordinates/shroud_long_inlet.curve
BLADE_COORDINATES_FILEPATH = coordinates/profile.curve

; Type of the blade leading and trailing edge (as many as number of blades)
BLADE_INLET_TYPE = axial
BLADE_OUTLET_TYPE = axial

; Method used for the camber reconstruction (regression or interpolation)
BLADES_CAMBER_RECONSTRUCTION = interpolation

; Verbosity
VERBOSITY = True

; Specify if you wish to normalize all the fields
NORMALIZE_DATA = False

; Specify True if you want to visualize the plots generated by the code for debugging
VISUAL_DEBUG = False

; Type of trim for every block (axial or radial)
BLOCKS_TRIM_TYPE = axial, axial, axial

MULTIBLOCK_DRIVER_TYPE = multiblock

BLADE_PROFILES_SPLINE_ORDER = 1

; Specify the types of output required. Possible choices are (turbobfm, su2mesh, meridional_paraview_splines, pickle)
OUTPUT_TYPE = turbobfm, su2mesh, meridional_paraview_splines, pickle, su2bfm



[BFM DATA]

; Number of blades for every blade row
BLADES_NUMBER = 36

; Insert the name of the machine for plot names
MACHINE_NAME = NR37

ROTATION_FACTORS = 1
