[CFD PROCESSING]

; Gamma of the fluid (e.g. 1.4)
GAMMA_FLUID = 1.4

; Type of mesh (default, sigmoid)
MESH_TYPE = default

; Mesh generation method (elliptic)
MESH_GENERATION_METHOD = elliptic

; Grid Orthogonality during elliptic smoothing (True or False)
GRID_ORTHOGONALITY = True

; Regression of the fields and gradients with 4th order polynomial (True or False)
STANDARD_REGRESSION = False

; Type of domains representated by the blocks (unbladed, rotor, or stator)
BLOCKS_TYPE = ['unbladed', 'rotor', 'unbladed']

; Number of points in the streamwise direction (same length of blocks_type)
STREAMWISE_POINTS = [15, 15, 28]

; Number of points in the spanwise direction (only one value)
SPANWISE_POINTS = 15

; Filepath to the file storing the CFD dataset
CFD_FILEPATH = ../data/cfd/nasar37_p128.5.csv

; File type of the file storing the CFD dataset
CFD_FILETYPE = Ansys2D

; Do you want to filter the fields?
MULTIBLOCK_FILTERING = False

; Do you want to smooth the fields in the neighborhood of the blade leading edge?
SHOCK_SMOOTHING = False

; Interpolation method to project CFD data on the working grid
CFD_SOLUTION_INTERPOLATION_METHOD = linear

; blocks to consider
INLET_BLOCK = True
BLADE_BLOCK = True
OUTLET_BLOCK = True

; Interpolation method used to compute the gradients on the working grid
GRADIENT_INTERPOLATION_METHOD = linear

; Reference quantities, in SI units
RHO_REF = 1.014
X_REF = 0.252
RPM_REF = 17189
T_REF = 288.15

; Shaft rotating speed in rpm
SHAFT_RPM = -17189

; Dimensions of the coordinates in the geometry files
COORDINATES_FILE_UNITS = cm

; Coefficients for the sigmoid stretching of the grid
SIGMOID_STREAM_COEFFICIENT = 12
SIGMOID_SPAN_COEFFICIENT = 12

; Filepath of the hub,shroud and blade geometry files
HUB_COORDINATES_FILEPATH = ../data/coordinates/hub.curve
SHROUD_COORDINATES_FILEPATH = ../data/coordinates/shroud.curve
BLADE_COORDINATES_FILEPATH = ../data/coordinates/profile.curve

; Type of the blade leading and trailing edge
BLADE_INLET_TYPE = axial
BLADE_OUTLET_TYPE = axial

; Verbosity
VERBOSITY = True

; Specify if you wish to normalize all the fields
NORMALIZE_DATA = True

; Specify if you wish to clip the BFM fields to be physically true (e.g. Loss Force always higher than zero)
CLIPPING_BFM = True





[SUN MODEL]

; Specify the filepath of the pickle object containing the meridional flow field data
MERIDIONAL_PICKLE_FILEPATH = ../../../../../Grid/test_cases/nasa_rotor_37/p128.5_regressed/data/pickle/nasar37_p128_15_15_28_15.pickle

; Specify which routine to use for the spectral-physic gradients evaluation (numpy, findiff)
GRID_TRANSFORMATION_GRADIENT_ROUTINE = findiff

; Specify the order of the gradients (even number)
GRID_TRANSFORMATION_GRADIENT_ORDER = 6

; Specify harmomic order of the analysis
CIRCUMFERENTIAL_HARMONIC_ORDER = 1

; Specify if you wish to normalize equations because the data in the pickle are dimensional
NORMALIZE_INSTABILITY_EQUATIONS = False

; Specify the center of the eigenvalue research
OMEGA_EIGV_RESEARCH_CENTER = 0

; Specify the number of eigenvalues to find with the Arnoldi Algorithm
NUMBER_EIGV_RESEARCH = 50

; Specify the boundary conditions for the problem. Available choices: zero perturbation, zero pressure, euler wall,
; compressor inlet, compressor outlet
INLET_BC = zero perturbation
HUB_BC = euler wall
SHROUD_BC = euler wall
OUTLET_BC = zero pressure