[COMPRESSION SYSTEM]

; Rotational speed [rpm]
RPM = 80e3

; Reference radius [m]
REFERENCE_RADIUS = 13e-3

; Speed of sound [m/s]
SOUND_SPEED = 340

; Plenum volume [m^3] (stable)
PLENUM_VOLUME = 0.015

; Inlet diameter [m]
INLET_DUCT_DIAMETER = 30.4e-3 

; Inlet length [m]
INLET_DUCT_LENGTH = 2.0

; Throttle diameter [m]
THROTTLE_DUCT_DIAMETER = 25e-3

; Throttle length [m]
THROTTLE_DUCT_LENGTH = 2.0

; Valve coefficient (2.85 is unstable, 2.8 is stable depending on parameters)
K_VALVE = 3.0


[COMPRESSOR]

; Unstalled characteristic coefficients
PSI_C_0_CHAR = 0.3
W_CHAR = 0.25
H_CHAR = 0.18

[SIMULATION]

; Max time of simulation [s]
MAX_TIME = 5

[MOORE GREITZER]

; Lag parameter
A_LAG = 0.286

; Moore parameter
M_PARAM = 1.75
