[CFD PROCESSING]

; Gamma of the fluid (e.g. 1.4)
GAMMA_FLUID = 1.4

; Mesh generation method (elliptic or TFI)
MESH_GENERATION_METHOD = TFI

; Coefficients for the sigmoid stretching of the grid blocks
SIGMOID_STREAM_COEFFICIENTS = 1, 1, 1, 1, 1, 1, 1

; Coefficient for the stretching in the spanwise direction (unique value)
SIGMOID_SPAN_COEFFICIENT = 1.3

; Grid Orthogonality during elliptic smoothing (True or False)
GRID_ORTHOGONALITY = True

; Type of domains representated by the blocks (unbladed, rotor, or stator)
BLOCKS_TYPE = unbladed, rotor, unbladed, stator, unbladed, stator, unbladed

; Number of points in the streamwise direction for each block
STREAMWISE_POINTS = 100, 20, 10, 20, 15, 40, 10

; Number of points in the spanwise direction (only one value)
SPANWISE_POINTS = 40

; Topology for the blocks (inlet, internal or outlet) to decide about the stretching type
BLOCKS_TOPOLOGY = inlet, internal, internal, internal, internal, internal, outlet

; Scaling of the coordinates if needed
X_REF = 1

; RPM of the shaft for each block
SHAFT_RPM = 0, -20000, 0, 0, 0, 0, 0

; Dimensions of the coordinates in the geometry curve files (cm, m, in) to convert everything in meters
COORDINATES_FILE_UNITS = m

; Filepath of the hub,shroud and blade (multiple if needed) geometry files
HUB_COORDINATES_FILEPATH = coordinates/Stator29_hub.curve
SHROUD_COORDINATES_FILEPATH = coordinates/Stator29_shroud.curve
BLADE_COORDINATES_FILEPATH = coordinates/Rotor16_profile.curve, coordinates/Stator29_profile.curve, coordinates/OGV5_profile.curve

; Type of the blade leading and trailing edge (as many as number of blades)
BLADE_INLET_TYPE = axial, axial, axial
BLADE_OUTLET_TYPE = axial, axial, axial

; Method used for the camber reconstruction (regression or interpolation)
BLADES_CAMBER_RECONSTRUCTION = interpolation, interpolation, interpolation

; Verbosity
VERBOSITY = True

; Specify if you wish to normalize all the fields
NORMALIZE_DATA = False

; Specify True if you want to visualize the plots generated by the code for debugging
VISUAL_DEBUG = False

; Type of trim for every block (axial or radial)
BLOCKS_TRIM_TYPE = axial, axial, axial, axial, axial, axial, axial

; Specify the type of grid generation type (full_machine=single block from inlet to outlet, single_blade=single block for the blade requested, multiblock=standard multiblock way)
MULTIBLOCK_DRIVER_TYPE = multiblock

BLADE_PROFILES_SPLINE_ORDER = 1, 1, 1

; Specify if you want to invert the axial coordinates
INVERT_AXIAL_COORDINATES = yes

BLADE_EDGES_EXTRAPOLATION_COEFFICIENT = 0.025, 0.025, 0.025

OUTPUT_TYPE = none

[BFM DATA]

; Number of blades for every blade row
BLADES_NUMBER = 16, 29, 5

; Insert the name of the machine for plot names
MACHINE_NAME = TUD-GLRa

ROTATION_FACTORS = 1, 0, 0
