[CFD PROCESSING]

; Gamma of the fluid (e.g. 1.4)
GAMMA_FLUID = 1.4

; Type of domains representated by the blocks (unbladed, rotor, or stator)
BLOCKS_TYPE = ['unbladed', 'unbladed']

; Number of points in the streamwise direction (same length of blocks_type)
STREAMWISE_POINTS = [60]

; Number of points in the spanwise direction (only one value)
SPANWISE_POINTS = 20


; Do you want to smooth the fields in the neighborhood of the blade leading edge?
SHOCK_SMOOTHING = False

; Reference quantities, in SI units
RHO_REF = 1.2095
X_REF = 0.1826
RPM_REF = 266.875
T_REF = 288

; Shaft rotating speed in rpm
SHAFT_RPM = 0

; Dimensions of the coordinates in the geometry files
COORDINATES_FILE_UNITS = cm

; Coefficients for the sigmoid stretching of the grid
SIGMOID_STREAM_COEFFICIENT = 12
SIGMOID_SPAN_COEFFICIENT = 12

; Filepath of the hub,shroud and blade geometry files
HUB_COORDINATES_FILEPATH = data/coordinates/hub.curve
SHROUD_COORDINATES_FILEPATH = data/coordinates/shroud.curve
BLADE_COORDINATES_FILEPATH = data/coordinates/profile.curve

; Type of the blade leading and trailing edge
BLADE_INLET_TYPE = axial
BLADE_OUTLET_TYPE = axial

; Verbosity
VERBOSITY = True

; Specify if you wish to normalize all the fields
NORMALIZE_DATA = True

; Specify if you wish to clip the BFM fields to be physically true (e.g. Loss Force always higher than zero)
CLIPPING_BFM = True





[SUN MODEL]

; Specify the filepath of the pickle object containing the meridional flow field data
MERIDIONAL_PICKLE_FILEPATH = ../../../Grid/testcases/nasa_rotor_37/data/pickle/nasar37_p130_5_5_5_5.pickle

; Specify which routine to use for the spectral-physic gradients evaluation (numpy, findiff)
GRID_TRANSFORMATION_GRADIENT_ROUTINE = numpy

; Specify the order of the gradients (even number)
GRID_TRANSFORMATION_GRADIENT_ORDER = 2

; Specify harmomic order of the analysis
CIRCUMFERENTIAL_HARMONIC_ORDER = 1

; Specify if you wish to normalize equations because the data in the pickle are dimensional
NORMALIZE_INSTABILITY_EQUATIONS = False

; Specify the center of the eigenvalue research
OMEGA_EIGV_RESEARCH_CENTER = 25000

; Specify the number of eigenvalues to find with the Arnoldi Algorithm
NUMBER_EIGV_RESEARCH = 8

DISABLE_BODY_FORCE = true

EULER_WALL_EQUATION = tangential velocity

; Specify the boundary conditions for the problem. Available choices: zero perturbation, zero pressure, euler wall,
; compressor inlet, compressor outlet
INLET_BC = zero pressure
HUB_BC = euler wall
SHROUD_BC = euler wall
OUTLET_BC = zero pressure