[COMPRESSION SYSTEM]

; Rotational speed [rpm]
RPM = 8e3

; Reference radius [m]
REFERENCE_RADIUS = 1

; Speed of sound [m/s]
SOUND_SPEED = 340

; Plenum volume [m^3] (stable)
PLENUM_VOLUME = 1

; Inlet diameter [m]
INLET_DUCT_DIAMETER = 0.3 

; Inlet length [m]
INLET_DUCT_LENGTH = 3.0

; Throttle diameter [m]
THROTTLE_DUCT_DIAMETER = 0.2

; Throttle length [m]
THROTTLE_DUCT_LENGTH = 3.0

; Valve coefficient (2.85 is unstable, 2.8 is stable depending on parameters)
K_VALVE = 4.2


[COMPRESSOR]

; Unstalled characteristic coefficients
PSI_C_0_CHAR = 0.3
W_CHAR = 0.2
H_CHAR = 0.175


; ; Flow coefficient array of values
; FLOW_COEFFS = 0.2, 0.4, 0.5, 0.6, 0.8

; ; Pressure coefficient array of values
; WORK_COEFFS = 0.5, 0.8, 0.95, 1.0, 0.8

[SIMULATION]

; Max time of simulation [s]
MAX_TIME = 1.5
