; CFD processing configurations
[CFD PROCESSING]
MESH_TYPE = default
STANDARD_REGRESSION = True
BLOCKS_NUMBER = 3
STREAMWISE_POINTS = [15, 20, 30]
SPANWISE_POINTS = 20
CFD_FILEPATH = data/meta/config_09_meridional_data_grads.csv
CFD_FILETYPE = ansys2D
MULTIBLOCK_FILTERING = False
SHOCK_SMOOTHING = False
CFD_SOLUTION_INTERPOLATION_METHOD = linear
INLET_BLOCK = True
BLADE_BLOCK = True
OUTLET_BLOCK = True
GRADIENT_INTERPOLATION_METHOD = linear
RHO_REF = 1.014
X_REF = 0.252
RPM_REF = -17189
T_REF = 288.15
CO0RDINATES_SCALING_FACTOR = 0.01  # cordinates of data files are in [cm]
SIGMOID_STREAM_COEFFICIENT = 10
SIGMOID_SPAN_COEFFICIENT = 10
HUB_COORDINATES_FILEPATH = nasa_rotor_37/cordinates/hub.curve
SHROUD_COORDINATES_FILEPATH = nasa_rotor_37/cordinates/shroud.curve
BLADE_COORDINATES_FILEPATH = nasa_rotor_37/cordinates/profile.curve