import os
import matplotlib.pyplot as plt
import numpy as np
from numpy import sin, cos, pi
import pickle
import pandas as pd
from utils.styles import *

#############################################################################################################################
#
#       SET OF TOOLS FOR CIRCUMFERENTIAL AVERAGE OF CFD DATASET OBTAINED WITH SU2 OR LUMINARY. 
#       THE INPUT NEEDED IS THE FOLDER WHERE ALL THE MERIDIONAL ARCS WITH DATA (OBTAINED WITH A PARAVIEW MACRO) 
#       ARE STORED IS CSV FILES. THE OUTPUT IS TWO PICKLE FILES CONTAINING THE AVERAGED FIELDS (RAW AND DENSITY-WEIGHTED)
#       FOR EACH QUANTITY IN THE DATASET ON THE MERIDIONAL GRID POINTS PROVIDED
#
#############################################################################################################################



def rotate_cartesian_to_cylindric_tensor(theta, M_cart):
    """
    Express the cartesian tensor (x,y,z) in cylindrical ref frame
    """
    Q = np.array([[np.cos(theta),  np.sin(theta), 0],
                  [-np.sin(theta), np.cos(theta), 0],
                  [0,           0,          1]])
    M_cyl = (Q.T)@M_cart@Q
    return M_cyl


def compute_average(field, weight=None):
    """Function to compute circumferential average

    Args:
        field (np.ndarray): 1D array of the field values along an arc, where the points are equidistant in theta (it must be true that integrals=averages)
        weight (np.ndarray, optional): Weighting function for the average. Defaults to None means no weighting, simple average.

    Returns:
        np.ndarray: scalar value of the average of the field
    """
    if weight is None:
        weight = np.ones_like(field)
    return np.sum(field*weight) / np.sum(weight)



def extract_grid_location(file_name):
    """Given the name of the file, return the indices associated to strem,span location

    Args:
        file_name (str): file contaning data on the arc at a specific location on the meridional plane

    Returns:
        int: indices of stream-span location
    """
    print('Averaging spline data: ' + file_name)
    file_name = file_name.strip('spline_data_')
    file_name = file_name.strip('.csv')
    file_name = file_name.split('_')
    nz = int(file_name[0])
    nr = int(file_name[1])
    return nz, nr



def circumferential_average_CFD_dataset(folderpath, extraction_method):
    """Compute the circumferential average of the dataset generated by the Paraview macro for circumferential average
    Args:
        folderpath (str): folder where all the arcs data are stored
        extraction_method (str, optional): Defaults to 'kiwada', which includes also all the data for Marble.
    """

    data_dir = folderpath
    files = [f for f in os.listdir(data_dir) if '.csv' in f]
    files = sorted(files)
    nz, nr = extract_grid_location(files[-1])
    nstream, nspan = nz+1, nr+1
    fields_thetaAvg = {}
    fields_densityAvg = {}

    output_folder = 'AveragedFields'
    os.makedirs(output_folder, exist_ok=True)
    
    if extraction_method.lower() == 'kiwada':
        fields_rawAvg, fields_densityAvg, fields_massFlowAvg = kiwada_postprocessing(folderpath, files, nstream, nspan)
    elif extraction_method.lower() == 'marble': 
        fields_rawAvg, fields_densityAvg, fields_massFlowAvg = marble_postprocessing(folderpath, files, nstream, nspan)
    else:
        raise ValueError('Extraction method not recognized. Please choose between Kiwada and Marble')
    
    filename = 'meridionalFields_rawAvg.pik'
    with open(output_folder + '/' + filename, 'wb') as f:
        pickle.dump(fields_rawAvg, f)
        print('Raw Average Fields saved in ' + output_folder + '/' + filename)
        
    filename = 'meridionalFields_densityAvg.pik'
    with open(output_folder + '/' + filename, 'wb') as f:
        pickle.dump(fields_densityAvg, f)
        print('Density-weighted Average Fields saved in ' + output_folder + '/' + filename)
        
    filename = 'meridionalFields_massFlowAvg.pik'
    with open(output_folder + '/' + filename, 'wb') as f:
        pickle.dump(fields_massFlowAvg, f)
        print('Mass flow-weighted Average Fields saved in ' + output_folder + '/' + filename)
        


def kiwada_postprocessing(folderpath, files, nstream, nspan, visual_debug=False):
    """Compute the circuferential average of all quantities needed by the kiwada extraction method

    Returns:
        dict: dictionaries contanin the raw and the density-weighted average of the fields
    """
    # first of all read the meridional grid
    zgrid = np.zeros((nstream, nspan))
    rgrid = np.zeros((nstream, nspan))
    for iFile, file in enumerate(files):
        df = pd.read_csv(folderpath + '/' + file)
        splineData = df.to_dict('list')
        splineData = {key: np.array(value) for key, value in splineData.items()}
        
        x = splineData['Points_0']
        y = splineData['Points_1']
        z = splineData['Points_2']
        r = np.sqrt(x ** 2 + y ** 2)
        theta = np.arctan2(y, x)
        stream_id, span_id = extract_grid_location(file)
        
        zgrid[stream_id, span_id] = np.mean(z)
        rgrid[stream_id, span_id] = np.mean(r)
    
    for iFile, file in enumerate(files):
        df = pd.read_csv(folderpath + '/' + file)
        splineData = df.to_dict('list')
        splineData = {key: np.array(value) for key, value in splineData.items()}
        
        x = splineData['Points_0']
        y = splineData['Points_1']
        z = splineData['Points_2']
        r = np.sqrt(x ** 2 + y ** 2)
        theta = np.arctan2(y, x)
        stream_id, span_id = extract_grid_location(file)
        
        if span_id == 0:
            deltaZ = zgrid[stream_id, span_id+1] - zgrid[stream_id, span_id]
            deltaR = rgrid[stream_id, span_id+1] - rgrid[stream_id, span_id]
        elif span_id == nspan-1:
            deltaZ = zgrid[stream_id, span_id] - zgrid[stream_id, span_id - 1]
            deltaR = rgrid[stream_id, span_id] - rgrid[stream_id, span_id - 1]
        else:
            deltaZ = zgrid[stream_id, span_id+1] - zgrid[stream_id, span_id - 1]
            deltaR = rgrid[stream_id, span_id+1] - rgrid[stream_id, span_id - 1]
        deltaLength = np.sqrt(deltaZ**2 + deltaR**2)
        
        # get the normal rotating 90 degree clockwise the tangential vector dz*i + dr*j
        normalAxial = deltaR/deltaLength
        normalRadial = -deltaZ/deltaLength
        
        splineData['Axial_Coordinate'] = z
        splineData['Radial_Coordinate'] = r
        splineData['Velocity_Radial'] = splineData['Velocity (m/s)_0']*np.cos(theta)+splineData['Velocity (m/s)_1']*np.sin(theta)
        splineData['Velocity_Tangential'] = -splineData['Velocity (m/s)_0']*np.sin(theta)+splineData['Velocity (m/s)_1']*np.cos(theta)
        drag_speed_tangential = -splineData['Grid Velocity (m/s)_0']*np.sin(theta) + splineData['Grid Velocity (m/s)_1']*np.cos(theta)
        splineData['Velocity_Tangential_Relative'] = splineData['Velocity_Tangential'] - drag_speed_tangential
        splineData['Velocity_Axial'] = splineData['Velocity (m/s)_2']
        
        # process of velocity gradients
        duxdx = splineData['Velocity_Gradient (1/s)_0']
        duxdy = splineData['Velocity_Gradient (1/s)_1']
        duxdz = splineData['Velocity_Gradient (1/s)_2']
        duydx = splineData['Velocity_Gradient (1/s)_3']
        duydy = splineData['Velocity_Gradient (1/s)_4']
        duydz = splineData['Velocity_Gradient (1/s)_5']
        duzdx = splineData['Velocity_Gradient (1/s)_6']
        duzdy = splineData['Velocity_Gradient (1/s)_7']
        duzdz = splineData['Velocity_Gradient (1/s)_8']
        
        # compute turbulent cartesian stress tensor
        div_u = duxdx+duydy+duzdz
        mu = (splineData['Eddy Viscosity (N·s/m²)'])*splineData['Density (kg/m³)']

        tauxx = mu*(2*duxdx)-2/3*mu*div_u
        tauyy = mu*(2*duydy)-2/3*mu*div_u
        tauzz_cart = mu*(2*duzdz)-2/3*mu*div_u
        tauxy = mu*(duydx+duxdy)
        tauyz = mu*(duydz+duzdy)
        tauxz = mu*(duxdz+duzdx)
        trace_cart = tauxx+tauyy+tauzz_cart
        
        taurr = np.zeros_like(duxdx) 
        tautt = np.zeros_like(duxdx) 
        tauzz_cyl = np.zeros_like(duxdx) 
        taurt = np.zeros_like(duxdx) 
        taurz = np.zeros_like(duxdx) 
        tautz = np.zeros_like(duxdx) 
        for i in range(len(tauxz)):
            TAU = np.zeros((3,3))
            TAU[0,0] = tauxx[i]
            TAU[0,1] = tauxy[i]
            TAU[0,2] = tauxz[i]
            TAU[1,0] = tauxy[i]
            TAU[1,1] = tauyy[i]
            TAU[1,2] = tauyz[i]
            TAU[2,0] = tauxz[i]
            TAU[2,1] = tauyz[i]
            TAU[2,2] = tauzz_cart[i]
            TAU_cyl = rotate_cartesian_to_cylindric_tensor(theta[i], TAU)
            taurr[i] = TAU_cyl[0,0]
            tautt[i] = TAU_cyl[1,1]
            tauzz_cyl[i] = TAU_cyl[2,2]
            taurt[i] = TAU_cyl[0,1]
            taurz[i] = TAU_cyl[0,2]
            tautz[i] = TAU_cyl[1,2]
        splineData['tau_rr'] = taurr
        splineData['tau_tt'] = tautt
        splineData['tau_zz'] = tauzz_cyl
        splineData['tau_rt'] = taurt
        splineData['tau_rz'] = taurz
        splineData['tau_tz'] = tautz
        
        splineData['Kiwada_Term_A1'] = splineData['Density (kg/m³)'] * splineData['Velocity_Axial']**2 + splineData['Pressure (Pa)'] - tauzz_cyl
        splineData['Kiwada_Term_A2'] = splineData['Density (kg/m³)'] * splineData['Velocity_Axial']*splineData['Velocity_Radial'] - taurz
        splineData['Kiwada_Term_R2'] = splineData['Density (kg/m³)'] * splineData['Velocity_Radial']**2 + splineData['Pressure (Pa)'] - taurr
        splineData['Kiwada_Term_R3'] = splineData['Density (kg/m³)'] * splineData['Velocity_Tangential']**2 + splineData['Pressure (Pa)'] - tautt
        splineData['Kiwada_Term_T1'] = splineData['Density (kg/m³)'] * splineData['Velocity_Axial']*splineData['Velocity_Tangential'] - tautz
        splineData['Kiwada_Term_T2'] = splineData['Density (kg/m³)'] * splineData['Velocity_Tangential']*splineData['Velocity_Radial'] - taurt    
        
        if visual_debug and iFile == 0:
            plt.figure()
            plt.plot(theta*180/np.pi, tauxx, '.', label=r'$\tau_{xx}$')
            plt.plot(theta*180/np.pi, tauyy, '.', label=r'$\tau_{yy}$')
            plt.plot(theta*180/np.pi, tauzz_cart, '.', label=r'$\tau_{zz}$')
            plt.plot(theta*180/np.pi, trace_cart, '.', label=r'$\tau_{xx} + \tau_{yy} + \tau_{zz}$')
            plt.xlabel(r'$\theta$ [deg]')
            plt.ylabel(r'$\tau$ [Pa]')
            plt.legend()

            plt.figure()
            plt.plot(theta*180/np.pi, tauxx, '.', label=r'$\tau_{xx}$')
            plt.plot(theta*180/np.pi, tauyy, '.', label=r'$\tau_{yy}$')
            plt.plot(theta*180/np.pi, tauzz_cart, '.', label=r'$\tau_{zz}$')
            plt.plot(theta*180/np.pi, tauxy, '.', label=r'$\tau_{xy}$')
            plt.plot(theta*180/np.pi, tauxz, '.', label=r'$\tau_{xz}$')
            plt.plot(theta*180/np.pi, tauyz, '.', label=r'$\tau_{yz}$')
            plt.xlabel(r'$\theta$ [deg]')
            plt.ylabel(r'$\tau$ [Pa]')
            plt.legend()
            
            trace_cyl = taurr+tautt+tauzz_cyl
            plt.figure()
            plt.plot(theta*180/pi, taurr, '.', label=r'$\tau_{rr}$')
            plt.plot(theta*180/pi, tautt, '.', label=r'$\tau_{\theta \theta}$')
            plt.plot(theta*180/pi, tauzz_cyl, '.', label=r'$\tau_{zz}$')
            plt.plot(theta*180/pi, trace_cyl, '.', label=r'$\tau_{rr} + \tau_{\theta} + \tau_{zz}$')
            plt.xlabel(r'$\theta$ [deg]')
            plt.ylabel(r'$\tau$ [Pa]')
            plt.legend()

            plt.figure()
            plt.plot(theta*180/pi, trace_cart, 'o', mfc='none', label='Cartesian')
            plt.plot(theta*180/pi, trace_cyl, 'x', label='Cylindrical')
            plt.xlabel(r'$\theta$ [deg]')
            plt.ylabel(r'Tr$(\tau)$ [Pa]')
            plt.legend()

            plt.figure()
            plt.plot(theta*180/pi, tauzz_cart, 'o', mfc='none', label='Cartesian')
            plt.plot(theta*180/pi, tauzz_cyl, 'x', label='Cylindrical')
            plt.xlabel(r'$\theta$ [deg]')
            plt.ylabel(r'$\tau_{zz}$ [Pa]')
            plt.legend()
            
            plt.figure()
            plt.plot(theta*180/pi, taurr, '.', label=r'$\tau_{rr}$')
            plt.plot(theta*180/pi, tautt, '.', label=r'$\tau_{\theta \theta}$')
            plt.plot(theta*180/pi, tauzz_cyl, '.', label=r'$\tau_{zz}$')
            plt.plot(theta*180/pi, taurt, '.', label=r'$\tau_{r \theta}$')
            plt.plot(theta*180/pi, taurz, '.', label=r'$\tau_{r z}$')
            plt.plot(theta*180/pi, tautz, '.', label=r'$\tau_{\theta z}$')
            plt.xlabel(r'$\theta$ [deg]')
            plt.ylabel(r'$\tau$ [Pa]')
            plt.legend()

        if iFile == 0: # initialize the field_grids dictionary
            fields_rawAvg = {key: np.zeros((nstream, nspan)) for key in splineData.keys()}
            fields_densityAvg = {key: np.zeros((nstream, nspan)) for key in splineData.keys()}
            fields_massFlowAvg = {key: np.zeros((nstream, nspan)) for key in splineData.keys()}
            
        for key in splineData.keys():
            field = splineData[key]
            density = splineData['Density (kg/m³)']
            velocityAxial = splineData['Velocity_Axial']
            velocityRadial = splineData['Velocity_Radial']
            
            normalAxialSpline = np.zeros_like(velocityAxial) + normalAxial
            normalRadialSpline = np.zeros_like(velocityRadial) + normalRadial
            massFlowWeight = density * (normalAxialSpline * velocityAxial + normalRadialSpline * velocityRadial)
            fields_rawAvg[key][stream_id, span_id] = compute_average(field)
            fields_densityAvg[key][stream_id, span_id] = compute_average(field, density)
            fields_massFlowAvg[key][stream_id, span_id] = compute_average(field, massFlowWeight)
        
    return fields_rawAvg, fields_densityAvg, fields_massFlowAvg



def marble_postprocessing(folderpath, files, nstream, nspan):
    
    # first of all read the meridional grid
    zgrid = np.zeros((nstream, nspan))
    rgrid = np.zeros((nstream, nspan))
    for iFile, file in enumerate(files):
        df = pd.read_csv(folderpath + '/' + file)
        splineData = df.to_dict('list')
        splineData = {key: np.array(value) for key, value in splineData.items()}
        
        x = splineData['Points_0']
        y = splineData['Points_1']
        z = splineData['Points_2']
        r = np.sqrt(x ** 2 + y ** 2)
        theta = np.arctan2(y, x)
        stream_id, span_id = extract_grid_location(file)
        
        zgrid[stream_id, span_id] = np.mean(z)
        rgrid[stream_id, span_id] = np.mean(r)
    
    # plt.figure()
    # plt.scatter(zgrid, rgrid, 'b.')
    # plt.show()
        
    for iFile, file in enumerate(files):
        df = pd.read_csv(folderpath + '/' + file)
        splineData = df.to_dict('list')
        splineData = {key: np.array(value) for key, value in splineData.items()}
            
        splineData['Velocity_Radial'] = splineData['Velocity (m/s)_0']*np.cos(theta)+splineData['Velocity (m/s)_1']*np.sin(theta)
        splineData['Velocity_Tangential'] = -splineData['Velocity (m/s)_0']*np.sin(theta)+splineData['Velocity (m/s)_1']*np.cos(theta)
        drag_speed_tangential = -splineData['Grid Velocity (m/s)_0']*np.sin(theta) + splineData['Grid Velocity (m/s)_1']*np.cos(theta)
        splineData['Velocity_Tangential_Relative'] = splineData['Velocity_Tangential'] - drag_speed_tangential
        splineData['Velocity_Axial'] = splineData['Velocity (m/s)_2']

        if iFile == 0: # initialize the field_grids dictionary
            fields_rawAvg = {key: np.zeros((nstream, nspan)) for key in splineData.keys()}
            fields_densityAvg = {key: np.zeros((nstream, nspan)) for key in splineData.keys()}
            fields_axialMomentumAvg = {key: np.zeros((nstream, nspan)) for key in splineData.keys()}
            
        for key in splineData.keys():
            field = splineData[key]
            density = splineData['Density (kg/m³)']
            axialMomentum = splineData['Density (kg/m³)']*splineData['Velocity_Axial']
            fields_rawAvg[key][stream_id, span_id] = compute_average(field)
            fields_densityAvg[key][stream_id, span_id] = compute_average(field, density)
            fields_axialMomentumAvg[key][stream_id, span_id] = compute_average(field, axialMomentum)
            
    return fields_rawAvg, fields_densityAvg, fields_axialMomentumAvg
