[SUN MODEL]

; Gamma of the fluid (e.g. 1.4)
GAMMA_FLUID = 1.4

; Specify which routine to use for the spectral-physic gradients evaluation (numpy, findiff)
GRID_TRANSFORMATION_GRADIENT_ROUTINE = findiff

; Specify the order of the gradients (even number)
GRID_TRANSFORMATION_GRADIENT_ORDER = 6

; Type of domains representated by the blocks (unbladed, rotor, or stator)
BLOCKS_TYPE = ['unbladed', 'unbladed']

; Specify harmomic order of the analysis
CIRCUMFERENTIAL_HARMONIC_ORDER = 1

; Specify the equation overwritten by the euler wall condition
EULER_WALL_EQUATION = radial velocity

; Specify the center of the eigenvalue research
OMEGA_EIGV_RESEARCH_CENTER = 24000

; Specify the number of eigenvalues to find with the Arnoldi Algorithm
NUMBER_EIGV_RESEARCH = 8

BOUNDARY_INTERFACE_GRADIENT_METHOD = collocation method

; Specify the boundary conditions for the problem. Available choices: zero perturbation, zero pressure, euler wall,
INLET_BC = zero pressure
HUB_BC = euler wall
SHROUD_BC = euler wall
OUTLET_BC = zero pressure

INPUT_GRID_FILES = Grids/data_30_10.pkl

BLOCK_TYPE = unbladed

RESULT_FILENAME = results_30_10

; Reference quantities for the normalization, in SI units
RHO_REF = 1.2095
X_REF = 0.1826
RPM_REF = 266.875
T_REF = 288

; Specify if you wish to normalize all the fields, to improve numerical stability
NORMALIZE_DATA = True