[CFD PROCESSING]

; Gamma of the fluid (e.g. 1.4)
GAMMA_FLUID = 1.4

; Type of domains representated by the blocks (unbladed, rotor, or stator)
BLOCKS_TYPE = ['unbladed', 'unbladed']

; Reference quantities, in SI units
RHO_REF = 1.2095
X_REF = 0.1826
RPM_REF = 266.875
T_REF = 288

; Shaft rotating speed in rpm
SHAFT_RPM = 0

STREAMWISE_POINTS = [30, 30]
SPANWISE_POINTS = 20

; Verbosity
VERBOSITY = True

; Specify if you wish to normalize all the fields
NORMALIZE_DATA = True



[SUN MODEL]

; Specify which routine to use for the spectral-physic gradients evaluation (numpy, findiff)
GRID_TRANSFORMATION_GRADIENT_ROUTINE = numpy

; Specify the order of the gradients (even number)
GRID_TRANSFORMATION_GRADIENT_ORDER = 2

; Specify harmomic order of the analysis
CIRCUMFERENTIAL_HARMONIC_ORDER = 1

; Specify if you wish to normalize equations because the data in the pickle are dimensional
NORMALIZE_INSTABILITY_EQUATIONS = False

; Specify the center of the eigenvalue research
OMEGA_EIGV_RESEARCH_CENTER = 0

; Specify the number of eigenvalues to find with the Arnoldi Algorithm
NUMBER_EIGV_RESEARCH = 5

; Specify the boundary conditions for the problem. Available choices: zero perturbation, zero pressure, euler wall,
; compressor inlet, compressor outlet
INLET_BC = zero pressure
HUB_BC = euler wall
SHROUD_BC = euler wall
OUTLET_BC = zero pressure